/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SbbCard {
    }
    interface SbbCardLabel {
    }
    interface SbbTab {
        "active": boolean;
        "label"?: string;
    }
    interface SbbTabGroup {
        "selectedIndex": number;
    }
    interface SbbTabLabel {
    }
}
declare global {
    interface HTMLSbbCardElement extends Components.SbbCard, HTMLStencilElement {
    }
    var HTMLSbbCardElement: {
        prototype: HTMLSbbCardElement;
        new (): HTMLSbbCardElement;
    };
    interface HTMLSbbCardLabelElement extends Components.SbbCardLabel, HTMLStencilElement {
    }
    var HTMLSbbCardLabelElement: {
        prototype: HTMLSbbCardLabelElement;
        new (): HTMLSbbCardLabelElement;
    };
    interface HTMLSbbTabElement extends Components.SbbTab, HTMLStencilElement {
    }
    var HTMLSbbTabElement: {
        prototype: HTMLSbbTabElement;
        new (): HTMLSbbTabElement;
    };
    interface HTMLSbbTabGroupElement extends Components.SbbTabGroup, HTMLStencilElement {
    }
    var HTMLSbbTabGroupElement: {
        prototype: HTMLSbbTabGroupElement;
        new (): HTMLSbbTabGroupElement;
    };
    interface HTMLSbbTabLabelElement extends Components.SbbTabLabel, HTMLStencilElement {
    }
    var HTMLSbbTabLabelElement: {
        prototype: HTMLSbbTabLabelElement;
        new (): HTMLSbbTabLabelElement;
    };
    interface HTMLElementTagNameMap {
        "sbb-card": HTMLSbbCardElement;
        "sbb-card-label": HTMLSbbCardLabelElement;
        "sbb-tab": HTMLSbbTabElement;
        "sbb-tab-group": HTMLSbbTabGroupElement;
        "sbb-tab-label": HTMLSbbTabLabelElement;
    }
}
declare namespace LocalJSX {
    interface SbbCard {
    }
    interface SbbCardLabel {
    }
    interface SbbTab {
        "active"?: boolean;
        "label"?: string;
        "onTabLabelChanged"?: (event: CustomEvent<void>) => void;
    }
    interface SbbTabGroup {
        "onSelectedTabChange"?: (event: CustomEvent<HTMLSbbTabElement>) => void;
        "selectedIndex"?: number;
    }
    interface SbbTabLabel {
        "onTabLabelContentChanged"?: (event: CustomEvent<void>) => void;
    }
    interface IntrinsicElements {
        "sbb-card": SbbCard;
        "sbb-card-label": SbbCardLabel;
        "sbb-tab": SbbTab;
        "sbb-tab-group": SbbTabGroup;
        "sbb-tab-label": SbbTabLabel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sbb-card": LocalJSX.SbbCard & JSXBase.HTMLAttributes<HTMLSbbCardElement>;
            "sbb-card-label": LocalJSX.SbbCardLabel & JSXBase.HTMLAttributes<HTMLSbbCardLabelElement>;
            "sbb-tab": LocalJSX.SbbTab & JSXBase.HTMLAttributes<HTMLSbbTabElement>;
            "sbb-tab-group": LocalJSX.SbbTabGroup & JSXBase.HTMLAttributes<HTMLSbbTabGroupElement>;
            "sbb-tab-label": LocalJSX.SbbTabLabel & JSXBase.HTMLAttributes<HTMLSbbTabLabelElement>;
        }
    }
}
